name: template
description: "Template for my projects."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^9.2.0
  injectable: ^2.7.1+4
  go_router: ^17.0.1
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  shared_preferences: ^2.5.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.12.0
  build_runner: ^2.10.4
  slang_build_runner: ^4.11.0
  freezed: ^3.2.4
  json_serializable: ^6.11.3


flutter:
  uses-material-design: true